---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/Concourse_Test_App/ci/build.sh
